### ISSUE TITLE
CB Tracker Tasks

### ISSUE THREAD

**Issue by ed3ath** [CryptoBlades/cb-tracker-mobile#5]
- [ ] Splash Screen
- [ ] Dashboard
	- [ ] Fetch and display dashboard data
- [ ] Accounts
	- [ ] Add account
	- [ ] Delete account
	- [ ] Rename account
	- [ ] Display account list
	- [ ] Reorder account list
	- [ ] Combat simulator
	- [ ] Fight history
- [ ] Rewards Calculator
- [ ] Statistics
- [ ] Options
	- [ ] Change network
	- [ ] Change conversion currency
